## @defgroup Methods-Missions-Segments-Climb Climb
# Climb mission methods containing the functions for setting up and solving a mission.
# @ingroup Methods-Missions-Segments

import Common
import Constant_Speed_Constant_Rate
import Constant_Mach_Constant_Rate
import Constant_Mach_Constant_Angle
import Linear_Mach_Constant_Rate
import Linear_Speed_Constant_Rate
import Constant_Throttle_Constant_Speed
import Constant_Dynamic_Pressure_Constant_Rate
import Constant_Speed_Constant_Angle
import Constant_Speed_Constant_Angle_Noise
import Constant_EAS_Constant_Rate
import Constant_Mach_Linear_Altitude
import Constant_Dynamic_Pressure_Constant_Angle
import Constant_Speed_Linear_Altitude
import Optimized