## @defgroup Methods-Missions-Segments-Cruise Cruise
# Cruise mission methods containing the functions for setting up and solving a mission.
# @ingroup Methods-Missions-Segments

import Common
import Constant_Mach_Constant_Altitude
import Constant_Speed_Constant_Altitude
import Constant_Mach_Constant_Altitude_Loiter
import Constant_Throttle_Constant_Altitude
import Variable_Cruise_Distance
import Constant_Dynamic_Pressure_Constant_Altitude_Loiter
import Constant_Acceleration_Constant_Altitude
import Constant_Pitch_Rate_Constant_Altitude
import Constant_Dynamic_Pressure_Constant_Altitude
import Constant_Speed_Constant_Altitude_Loiter