## @defgroup Methods-Aerodynamics-Fidelity_Zero-Drag Drag
# Functions to perform low-fidelity drag calculations
# @ingroup Methods-Aerodynamics-Fidelity_Zero


from miscellaneous_drag_aircraft import miscellaneous_drag_aircraft
from compressible_turbulent_flat_plate import compressible_turbulent_flat_plate
from compressible_mixed_flat_plate import compressible_mixed_flat_plate
from untrimmed import untrimmed
from total_aircraft import total_aircraft
from windmilling_drag import windmilling_drag
from asymmetry_drag import asymmetry_drag
from estimate_2ndseg_lift_drag_ratio import estimate_2ndseg_lift_drag_ratio